### PR TITLE
Add support for React JSX

### PR DESCRIPTION
**Pull request by ulken**
Adds support for React JSX(/TSX) by (optionally) looking for `className` (not only `class`).

### CODE REVIEW

**Comment by ulken** [comment]
@abdumu Thoughts?

I've used this locally and while it's not 100% perfect it works for most cases. It doesn't handle cases where not a plain quotation is used, but rather a helper function to generate classes, but that's expected/fine, I'd say.

**Comment by abdumu** [comment]
Thank you for adding this.

Could you add at least one test?

**Comment by ulken** [comment]
Sure, I'll give it a try. 

I found the test suite rather sparse, which is why I didn't add one to begin with.

**Comment by ulken** [comment]
Any plans of supporting 2.0? Either for this or `tailshift`.

**Comment by ulken** [comment]
On a related note: to be framework agnostic, have you considered simply using a regex similar to what [PurgeCSS](https://purgecss.com) does out-of-the-box?

```regex
/[^<>"'`\s]*[^<>"'`\s:]/g
```

To quote [Tailwind CSS](https://tailwindcss.com/docs/optimizing-for-production#writing-purgeable-html):

>This basically matches any string separated by spaces, quotes or angle brackets, including HTML tags, attributes, classes, and even the actual written content in your markup.

**Comment by ulken** [comment]
@abdumu Test added

**Comment by abdumu** [comment]
thanks

**Pull request merged**
