### PR TITLE
Add custom extensions support

### PR DESCRIPTION
**Pull request by austinkregel**
# Changes
 - Adds the ability to add custom file extensions to the search for files with the flags `--extentions=php,html` or `-e php,html`

Closes https://github.com/awssat/tailwindo/issues/5

### CODE REVIEW

**Comment by abdumu** [comment]
@austinkregel 

Could you fix the conflicts and also, filter the given extensions. like using array_map('trim', ..) then array_filter(...). Also it will be great to check if the given extension starts with a dot and remove it. 

These are suggestions. You could just fix the conflicts and I would make the rest.

**Comment by austinkregel** [comment]
Like I said I'm at work at the moment, so I won't be able to until tonight, but I sure can :)

**Comment by austinkregel** [comment]
@abdumu I believe that's everything :) Is there anything more I should add or change?

**Comment by abdumu** [comment]
@austinkregel great, thanks 👍🏼

**Pull request merged**
